### ISSUE TITLE
Add instructions to choose the UAssetGUI version number to 4.23 from dropdown

### ISSUE THREAD

**Issue by samjco** [AstroTechies/astroneermodding#13]
docs/guides/basicModding.rst # #

Now open the ``FloodLight_IT.uasset`` file in the ``TutorialMod`` folder using UAssetGUI. 

Needed addition
_Be sure to changed the UAssetGUI engine version (top-right dropdown) to 4.23 or else the uasset file 
will not load and you may receive an error message._

https://github.com/AstroTechies/astroneermodding/commit/1e1670d4d8f4beef52748201360f33934c702ec5

**Comment by konsti219** [comment]
Learn some GitHub. This is an issue, not a PR.
